name: app_core
description: "A new Flutter project."
version: 0.0.2
homepage:

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  google_fonts: ^6.3.3
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^6.3.0
  firebase_storage: ^13.0.4
  firebase_database: ^12.1.0
  firebase_analytics: ^12.0.4
  firebase_remote_config: ^6.1.2
  google_mobile_ads: ^6.0.0
  sign_in_with_apple: ^7.0.1
  flutter_screenutil: ^5.9.3
  dotted_border: ^3.1.0
  auto_size_text: ^3.0.0
  fpdart: ^1.2.0
  equatable: ^2.0.7
  copy_with_extension: ^11.0.0
  provider: ^6.1.5+1
  get_it: ^9.2.0
  blobs: ^2.0.0
  simple_animations: ^5.2.0
  modal_bottom_sheet: ^3.0.0
  loading_animation_widget: ^1.3.0
  connectivity_plus: ^7.0.0
  flutter_animate: ^4.5.2
  http: ^1.6.0
  shared_preferences: ^2.5.4
  purchases_flutter: ^9.6.2
  percent_indicator: ^4.2.5
  json_annotation: ^4.9.0
  url_launcher: ^6.3.2
  isoweek: ^1.1.4
  flutter_bounceable:
    git:
      url: https://github.com/njaistudio/flutter_bounceable.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: any
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  copy_with_extension_gen: ^11.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
   assets:
     - assets/images/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
flutter_intl:
  enabled: false
  class_name: CoreS
